version: '3.3'

# Application services
services:

  # Postgres Database.
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=adharaStore
      - POSTGRES_USER=omju
      - POSTGRES_PASSWORD=omauri.Postgres0691
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # Administrator pgAdmin to Postgres.
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=omju@mail.com
      - PGADMIN_DEFAULT_PASSWORD=omauri.Pgadmin0691
    ports:
      - 5050:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
